### ISSUE TITLE
Java kódolási stílus hozzáadása a közreműködési útmutatóhoz

### ISSUE THREAD

**Issue by kripod** [kripod/bme-vik-info#4]

**Comment by kripod** [comment]
@no372 Tudnál javasolni egy Java-ban használatos, népszerű és elterjedt kódolási stílust? :blush:

**Comment by kripod** [comment]
(Eddig ezt találtam: https://google.github.io/styleguide/javaguide.html)

**Comment by no372** [comment]
> [ **kripod**] commented
> (Eddig ezt találtam: [https://google.github.io/styleguide/javaguide.html])

_Szerintem_ lefed sokmindent, de kiegészíteném [ezzel].
A közeljövőben _megpróbálom_ összszedni az _alapvető_, illetve _legfontosabb_ stílus elemeket, majd  leírni _magyar nyelven_. Amint végzek, feltöltöm / linkelem.

[ **kripod**]: https://github.com/kripod
[https://google.github.io/styleguide/javaguide.html]: https://google.github.io/styleguide/javaguide.html
[ezzel]: http://geosoft.no/development/javastyle.html

**Comment by kripod** [comment]
@no372 Köszi szépen a segítséget! 😊 Jó ötlet a magyar nyelvű style guide, de szívesebben használnék irányadóként elterjedtebb, angol nyelvű írásokat. Persze a meglévő linkek mellett elfér még egy magyarra irányító hivatkozás is, hiszen *jelenleg* nem használunk lintert és CI alapú szigorú kódstílus-ellenőrzést.

Az #5-ös számú pull requesttel egyelőre megoldódtak a Java kódstílussal kapcsolatos kérdések, ezért ezt az issue-t lezárom.
